# Generated by Django 5.1.1 on 2024-10-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bavaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brandModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bavaria.brandnmaemodel'),
        ),
    ]
